import type { ClonedAsset, CrawlResult, ScrapeResult } from "./types.js";
import { cleanDocument, fragmentToJsx } from "./htmlToJsx.js";

/** Builds every file (preview/ and react-app/) for a scraped site, keyed by path relative to the output root. */
export function generateProject(scrape: ScrapeResult): Map<string, Buffer | string> {
  const files = new Map<string, Buffer | string>();
  const { html: cleanedHtml, bodyInnerHtml } = cleanDocument(scrape.html);
  const title = scrape.pageTitle || "Cloned Site";

  // --- preview/: a self-contained static clone, viewable as-is. ---
  files.set("preview/index.html", cleanedHtml);
  files.set("preview/styles.css", scrape.css);
  for (const asset of scrape.assets) {
    files.set(`preview/${asset.localPath}`, asset.data);
  }

  // --- react-app/: an editable Vite + React project reconstructing the same page. ---
  const jsxBody = fragmentToJsx(bodyInnerHtml);
  const appJsx = [
    `import "./App.css";`,
    "",
    `export default function App() {`,
    `  return (`,
    `    <>`,
    jsxBody || `      {/* (empty body) */}`,
    `    </>`,
    `  );`,
    `}`,
    "",
  ].join("\n");

  files.set("react-app/src/App.jsx", appJsx);
  files.set("react-app/src/App.css", scrape.css);
  files.set(
    "react-app/src/main.jsx",
    [
      `import { StrictMode } from "react";`,
      `import { createRoot } from "react-dom/client";`,
      `import App from "./App.jsx";`,
      "",
      `createRoot(document.getElementById("root")).render(`,
      `  <StrictMode>`,
      `    <App />`,
      `  </StrictMode>,`,
      `);`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/index.html",
    [
      `<!doctype html>`,
      `<html lang="en">`,
      `  <head>`,
      `    <meta charset="UTF-8" />`,
      `    <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `    <title>${title}</title>`,
      `  </head>`,
      `  <body>`,
      `    <div id="root"></div>`,
      `    <script type="module" src="/src/main.jsx"></script>`,
      `  </body>`,
      `</html>`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/vite.config.js",
    [
      `import { defineConfig } from "vite";`,
      `import react from "@vitejs/plugin-react";`,
      "",
      `export default defineConfig({`,
      `  plugins: [react()],`,
      `});`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/package.json",
    JSON.stringify(
      {
        name: "cloned-site",
        private: true,
        version: "0.0.1",
        type: "module",
        scripts: {
          dev: "vite",
          build: "vite build",
          preview: "vite preview",
        },
        dependencies: {
          react: "^18.3.1",
          "react-dom": "^18.3.1",
        },
        devDependencies: {
          "@vitejs/plugin-react": "^4.3.3",
          vite: "^5.4.10",
        },
      },
      null,
      2,
    ) + "\n",
  );
  for (const asset of scrape.assets) {
    files.set(`react-app/public/${asset.localPath}`, asset.data);
  }

  files.set(
    "README.md",
    [
      `# Cloned site: ${title}`,
      "",
      `Source: ${scrape.sourceUrl}`,
      "",
      "This bundle contains two folders:",
      "",
      "- \`preview/\` — a self-contained static HTML clone. Open `preview/index.html` " +
        "directly, or serve the folder, to see it as-is.",
      "- \`react-app/\` — the same page rebuilt as an editable Vite + React project.",
      "  ```",
      "  cd react-app",
      "  npm install",
      "  npm run dev",
      "  ```",
      "",
      "Generated by Website Cloner.",
      "",
    ].join("\n"),
  );

  return files;
}

/** Route path (e.g. "/", "/about", "/blog/post-1") for a crawled page, derived from its URL. */
function routePathFor(pageUrl: string): string {
  const pathname = decodeURIComponent(new URL(pageUrl).pathname);
  if (pathname === "" || pathname === "/") return "/";
  return pathname.endsWith("/") ? pathname.slice(0, -1) : pathname;
}

function folderFor(routePath: string): string {
  return routePath === "/" ? "" : routePath.slice(1);
}

function pascalCase(segment: string): string {
  return segment
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((word) => word[0]!.toUpperCase() + word.slice(1))
    .join("");
}

function componentNameFor(routePath: string, usedNames: Set<string>): string {
  const base = routePath === "/" ? "Home" : routePath.split("/").filter(Boolean).map(pascalCase).join("") || "Page";
  const safe = /^[A-Za-z]/.test(base) ? base : `Page${base}`;
  let name = `${safe}Page`;
  let suffix = 2;
  while (usedNames.has(name)) {
    name = `${safe}Page${suffix++}`;
  }
  usedNames.add(name);
  return name;
}

/**
 * A generated React app is a client-routed SPA: the browser's current URL can be any route
 * (e.g. "/blog/post-1"), but `public/` assets are always served from the site root. Relative
 * "assets/xxx" references (correct for the preview/ static files, which sit next to their own
 * assets folder) would resolve against the *current route*, not the site root, and 404 on any
 * non-root page - so react-app content needs root-absolute "/assets/xxx" references instead.
 */
function toRootAbsoluteAssetPaths(text: string): string {
  return text.replace(/(?<!\/)assets\//g, "/assets/");
}

/**
 * Builds a multi-page React project (react-router-dom) plus a matching multi-file static
 * preview, from a crawlSite() result.
 */
export function generateMultiPageProject(crawl: CrawlResult): Map<string, Buffer | string> {
  const files = new Map<string, Buffer | string>();
  const siteTitle = crawl.pages[0]?.pageTitle || "Cloned Site";

  const usedComponentNames = new Set<string>();
  const sharedAssets = new Map<string, ClonedAsset>();
  const routeEntries: { routePath: string; componentName: string }[] = [];
  const cssChunks: string[] = [];

  for (const page of crawl.pages) {
    const routePath = routePathFor(page.sourceUrl);
    const folder = folderFor(routePath);
    const { html: cleanedHtml, bodyInnerHtml } = cleanDocument(page.html);

    // --- preview/<folder>/: each page is a real, independently-navigable HTML file, so it
    // keeps its own sibling styles.css + assets/ (relative paths need no route-depth math). ---
    const previewDir = folder ? `preview/${folder}` : "preview";
    files.set(`${previewDir}/index.html`, cleanedHtml);
    files.set(`${previewDir}/styles.css`, page.css);
    for (const asset of page.assets) {
      files.set(`${previewDir}/${asset.localPath}`, asset.data);
      sharedAssets.set(asset.localPath, asset);
    }

    // --- react-app/src/pages/: one component per route, wired into a single SPA below. ---
    const componentName = componentNameFor(routePath, usedComponentNames);
    routeEntries.push({ routePath, componentName });
    const jsxBody = fragmentToJsx(toRootAbsoluteAssetPaths(bodyInnerHtml));
    files.set(
      `react-app/src/pages/${componentName}.jsx`,
      [
        `export default function ${componentName}() {`,
        `  return (`,
        `    <>`,
        jsxBody || `      {/* (empty body) */}`,
        `    </>`,
        `  );`,
        `}`,
        "",
      ].join("\n"),
    );

    if (page.css.trim()) cssChunks.push(page.css);
  }

  // Simple whole-string dedupe: pages that share an identical combined stylesheet (e.g. every
  // page loading the same site-wide CSS) shouldn't have it repeated per page.
  const combinedCss = [...new Set(cssChunks)].join("\n\n");
  files.set("react-app/src/App.css", toRootAbsoluteAssetPaths(combinedCss));

  const routeImports = routeEntries
    .map((r) => `import ${r.componentName} from "./pages/${r.componentName}.jsx";`)
    .join("\n");
  const routeElements = routeEntries
    .map((r) => `        <Route path={${JSON.stringify(r.routePath)}} element={<${r.componentName} />} />`)
    .join("\n");

  files.set(
    "react-app/src/App.jsx",
    [
      `import { BrowserRouter, Routes, Route } from "react-router-dom";`,
      routeImports,
      `import "./App.css";`,
      "",
      `export default function App() {`,
      `  return (`,
      `    <BrowserRouter>`,
      `      <Routes>`,
      routeElements,
      `      </Routes>`,
      `    </BrowserRouter>`,
      `  );`,
      `}`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/src/main.jsx",
    [
      `import { StrictMode } from "react";`,
      `import { createRoot } from "react-dom/client";`,
      `import App from "./App.jsx";`,
      "",
      `createRoot(document.getElementById("root")).render(`,
      `  <StrictMode>`,
      `    <App />`,
      `  </StrictMode>,`,
      `);`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/index.html",
    [
      `<!doctype html>`,
      `<html lang="en">`,
      `  <head>`,
      `    <meta charset="UTF-8" />`,
      `    <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `    <title>${siteTitle}</title>`,
      `  </head>`,
      `  <body>`,
      `    <div id="root"></div>`,
      `    <script type="module" src="/src/main.jsx"></script>`,
      `  </body>`,
      `</html>`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/vite.config.js",
    [
      `import { defineConfig } from "vite";`,
      `import react from "@vitejs/plugin-react";`,
      "",
      `export default defineConfig({`,
      `  plugins: [react()],`,
      `});`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/package.json",
    JSON.stringify(
      {
        name: "cloned-site",
        private: true,
        version: "0.0.1",
        type: "module",
        scripts: {
          dev: "vite",
          build: "vite build",
          preview: "vite preview",
        },
        dependencies: {
          react: "^18.3.1",
          "react-dom": "^18.3.1",
          "react-router-dom": "^6.28.0",
        },
        devDependencies: {
          "@vitejs/plugin-react": "^4.3.3",
          vite: "^5.4.10",
        },
      },
      null,
      2,
    ) + "\n",
  );
  for (const asset of sharedAssets.values()) {
    files.set(`react-app/public/${asset.localPath}`, asset.data);
  }

  files.set(
    "README.md",
    [
      `# Cloned site: ${siteTitle}`,
      "",
      `Crawled from: ${crawl.startUrl}`,
      `Pages: ${crawl.pages.length}`,
      "",
      "This bundle contains two folders:",
      "",
      "- `preview/` — a self-contained static multi-page HTML clone, one folder per route " +
        "(e.g. `preview/about/index.html`). Serve the folder to browse it as-is.",
      "- `react-app/` — the same pages rebuilt as an editable Vite + React project using " +
        "react-router-dom (one component per route under `src/pages/`).",
      "  ```",
      "  cd react-app",
      "  npm install",
      "  npm run dev",
      "  ```",
      "",
      "Generated by Website Cloner.",
      "",
    ].join("\n"),
  );

  return files;
}
