import type { ScrapeResult } from "./types.js";
import { cleanDocument, fragmentToJsx } from "./htmlToJsx.js";

/** Builds every file (preview/ and react-app/) for a scraped site, keyed by path relative to the output root. */
export function generateProject(scrape: ScrapeResult): Map<string, Buffer | string> {
  const files = new Map<string, Buffer | string>();
  const { html: cleanedHtml, bodyInnerHtml } = cleanDocument(scrape.html);
  const title = scrape.pageTitle || "Cloned Site";

  // --- preview/: a self-contained static clone, viewable as-is. ---
  files.set("preview/index.html", cleanedHtml);
  files.set("preview/styles.css", scrape.css);
  for (const asset of scrape.assets) {
    files.set(`preview/${asset.localPath}`, asset.data);
  }

  // --- react-app/: an editable Vite + React project reconstructing the same page. ---
  const jsxBody = fragmentToJsx(bodyInnerHtml);
  const appJsx = [
    `import "./App.css";`,
    "",
    `export default function App() {`,
    `  return (`,
    `    <>`,
    jsxBody || `      {/* (empty body) */}`,
    `    </>`,
    `  );`,
    `}`,
    "",
  ].join("\n");

  files.set("react-app/src/App.jsx", appJsx);
  files.set("react-app/src/App.css", scrape.css);
  files.set(
    "react-app/src/main.jsx",
    [
      `import { StrictMode } from "react";`,
      `import { createRoot } from "react-dom/client";`,
      `import App from "./App.jsx";`,
      "",
      `createRoot(document.getElementById("root")).render(`,
      `  <StrictMode>`,
      `    <App />`,
      `  </StrictMode>,`,
      `);`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/index.html",
    [
      `<!doctype html>`,
      `<html lang="en">`,
      `  <head>`,
      `    <meta charset="UTF-8" />`,
      `    <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `    <title>${title}</title>`,
      `  </head>`,
      `  <body>`,
      `    <div id="root"></div>`,
      `    <script type="module" src="/src/main.jsx"></script>`,
      `  </body>`,
      `</html>`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/vite.config.js",
    [
      `import { defineConfig } from "vite";`,
      `import react from "@vitejs/plugin-react";`,
      "",
      `export default defineConfig({`,
      `  plugins: [react()],`,
      `});`,
      "",
    ].join("\n"),
  );
  files.set(
    "react-app/package.json",
    JSON.stringify(
      {
        name: "cloned-site",
        private: true,
        version: "0.0.1",
        type: "module",
        scripts: {
          dev: "vite",
          build: "vite build",
          preview: "vite preview",
        },
        dependencies: {
          react: "^18.3.1",
          "react-dom": "^18.3.1",
        },
        devDependencies: {
          "@vitejs/plugin-react": "^4.3.3",
          vite: "^5.4.10",
        },
      },
      null,
      2,
    ) + "\n",
  );
  for (const asset of scrape.assets) {
    files.set(`react-app/public/${asset.localPath}`, asset.data);
  }

  files.set(
    "README.md",
    [
      `# Cloned site: ${title}`,
      "",
      `Source: ${scrape.sourceUrl}`,
      "",
      "This bundle contains two folders:",
      "",
      "- \`preview/\` — a self-contained static HTML clone. Open `preview/index.html` " +
        "directly, or serve the folder, to see it as-is.",
      "- \`react-app/\` — the same page rebuilt as an editable Vite + React project.",
      "  ```",
      "  cd react-app",
      "  npm install",
      "  npm run dev",
      "  ```",
      "",
      "Generated by Website Cloner.",
      "",
    ].join("\n"),
  );

  return files;
}
